itutor/urls.py
from django import urls
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.landing_page, name="landing_page"),
    path('admin/', admin.site.urls),
    path('authenticate/', include('login_logout.urls')),
    path('buat-kursus/', include('buat_kursus.urls')),
    path('sunting-kursus/', include('sunting_kursus.urls')),
    path('daftar-kursus/', include('daftar_kursus.urls')),
    path('detail-kursus/',include('detail_kursus.urls')),
    path('buat-feedback/',include('feedback.urls')),
    path('pengajuan-kursus/',include('pengajuan_kursus.urls')),
    path('pesan/', include('pesan.urls')),
    path('kursus-pengajar/', include('kursus_pengajar.urls')),
    path('verifikasi/', include('verifikasi_kursus.urls')),
    path('cari-kursus/', include('carikursus.urls')),
    path('register/', include('register.urls')),
    path('kursus-pelajar/', include('kursus_pelajar.urls')),
    path('profile-pengguna/', include('profile_pengguna.urls')),
]

login_logout/urls.py
from django.urls import path
from . import views

app_name = 'login_logout'
urlpatterns = [
    path('', views.login_page, name="login_url"),
    path('logout', views.logout_user, name="logout_url")
]

pesan/urls.py
from django.urls import path
from . import views

app_name = 'pesan'
urlpatterns = [
    path('add-contact/<id_pengajar>', views.add_contact, name="add_contact_url"),
    path('contacts', views.show_all_contact, name="contacts_url"),
    path('detail/<username>', views.show_all_pesan, name="message_url"),
]

register/urls.py
from django.urls import path
from .views import register_pelajar, register_pengajar, register, register_admin

app_name = 'register'
urlpatterns = [
    path('', register, name="register"),
    path('pelajar/', register_pelajar, name="register_pelajar"),
    path('pengajar/', register_pengajar, name="register_pengajar"),
    path('admin/', register_admin, name="register_admin"),
]

login_logout/models.py
from django.db import models

# Create your models here.

login_logout/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required

def login_page(request):
    response = {'hide_header': True, 'hide_footer': True}
    if request.user.is_authenticated:
        if request.user.is_staff:
            return redirect('verifikasi_kursus:pengajuan_url')
        else:
            return redirect('landing_page')
    else:
        if request.method == 'POST':
            username = request.POST.get('username')
            password = request.POST.get('password')
            user = authenticate(request, username = username, password = password)

            if user is not None:
                login(request, user)
                if user.is_staff:
                    return redirect('verifikasi_kursus:pengajuan_url')
                return redirect(request.POST.get('next') or 'landing_page')
            else:
                response['username'] = username
                response['message'] = 'Username atau password anda belum tepat'
        return render(request, 'login.html', response)

@login_required(login_url='login_logout:login_url')
def logout_user(request):
    logout(request)
    return redirect('landing_page')

login_logout/templates/login.html
{% extends 'app-shell.html' %}
{% load static %}

{% block meta %}
<title>i-Tutor | Login</title>
<link rel="stylesheet" href="{% static 'css/formBuat.css' %}">
<link rel="stylesheet" href="{% static 'css/login-form.css' %}">
{% endblock meta %}

{% block content %}
<div class="container-fluid" style="height: 100vh;">
    <div class="row" style="height: 100%;">
        <div class="col no-float kiri">
            <img src="{% static 'image/login.png' %}" width="300" height="400">
            <h1 style="font-size: 50px; font-weight: bold; margin-top: 20px; width: 340px;">
                Ada tutor untuk semua!
            </h1>
        </div>
        <div class="col no-float kanan">
            <div>
                <h1 class="title" style="font-size: 1.75rem; padding-top: 0;">Masuk ke akunmu</h1>
                <h4 style="font-size: 1.25rem;">Belum punya akun? <a href="{% url 'register:register' %}">Daftar sekarang!</a></h4>
                <hr class="line" width="100%">
            </div>
            <form method="POST" id="form-login">
                {% csrf_token %}
                {% if message %}
                    <p class="message">{{ message }}</p>
                {% endif %}
                <div class="form-group">
                    <label for="username">Username</label>
                    <input type="text" class="form-control" id="username" name="username" placeholder="Ketik username" value="{{ username }}">
                </div>
                <div class="form-group">
                    <label for="password">Password</label>
                    <input type="password" class="form-control" id="password" name="password" placeholder="Minimum 8 karakter">
                </div>
                <input type="hidden" name="next" value="{{ request.GET.next }}"/>
                <div class="flex-container">
                    <button style="border: 0;" type="submit" class="button accent-2">Login</button>
                    <button class="button outline-1" formaction="/">Batal</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock content %}