carikursus/urls.py
from django.urls import path
from .views import cari_kursus

app_name = 'carikursus'
urlpatterns = [
    path('', cari_kursus, name='cari_kursus'),
]

daftar_kursus/urls.py
from django.urls import path
from .views import daftar_kursus

app_name = 'daftar_kursus'
urlpatterns = [
    path('<int:id_kursus>', daftar_kursus, name='daftar_kursus'),
]

detail_kursus/urls.py
from django.urls import path
from . import views

app_name = 'detail_kursus'
urlpatterns = [
    path('<int:id_kursus>',views.detail_kursus,name='detail_kursus'),
]

itutor/urls.py
from django import urls
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.landing_page, name="landing_page"),
    path('admin/', admin.site.urls),
    path('authenticate/', include('login_logout.urls')),
    path('buat-kursus/', include('buat_kursus.urls')),
    path('sunting-kursus/', include('sunting_kursus.urls')),
    path('daftar-kursus/', include('daftar_kursus.urls')),
    path('detail-kursus/',include('detail_kursus.urls')),
    path('buat-feedback/',include('feedback.urls')),
    path('pengajuan-kursus/',include('pengajuan_kursus.urls')),
    path('pesan/', include('pesan.urls')),
    path('kursus-pengajar/', include('kursus_pengajar.urls')),
    path('verifikasi/', include('verifikasi_kursus.urls')),
    path('cari-kursus/', include('carikursus.urls')),
    path('register/', include('register.urls')),
    path('kursus-pelajar/', include('kursus_pelajar.urls')),
    path('profile-pengguna/', include('profile_pengguna.urls')),
]

kursus_pengajar/urls.py
from django.urls import path
from .views import kursus_pengajar, delete_kursus

app_name = 'kursus_pengajar'
urlpatterns = [
    path('', kursus_pengajar, name='kursus_pengajar'),
    path('delete/<int:pk>', delete_kursus, name='delete_kursus'),
]

pesan/urls.py
from django.urls import path
from . import views

app_name = 'pesan'
urlpatterns = [
    path('add-contact/<id_pengajar>', views.add_contact, name="add_contact_url"),
    path('contacts', views.show_all_contact, name="contacts_url"),
    path('detail/<username>', views.show_all_pesan, name="message_url"),
]

detail_kursus/models.py
from django.db import models

# Create your models here.

detail_kursus/views.py
from django.http.response import JsonResponse
from django.shortcuts import render
from django.template.loader import render_to_string
from buat_kursus.models import Kategori, Kursus
from daftar_kursus.models import Pendaftaran
from register.models import NonAdmin

# Create your views here.
def detail_kursus(request, id_kursus):
    kursus = Kursus.objects.get(id=id_kursus)
    pendaftaran = Pendaftaran.objects.filter(kursus_id=id_kursus).filter(status_pendaftar=3)

    
    # print(kursus)
    print(pendaftaran)
    response = {}
    response['kursus'] = kursus
    response['pendaftaran'] = pendaftaran
    if request.user.is_authenticated:
        user = NonAdmin.objects.get(pengguna_ptr_id=request.user.id)
        response['pengguna'] = user
        print(user.is_pelajar)
        print(user.is_pengajar)
        pendaftaran_pelajar_yang_boleh = Pendaftaran.objects.filter(kursus_id=id_kursus).filter(status_pendaftar=2).filter(pelajar_id=request.user.id)
        response['pelajar_valid'] = pendaftaran_pelajar_yang_boleh

    # print('pelajar: ',user.is_pelajar)
    # print('pengajar: ',user.is_pengajar)

    if len(pendaftaran) != 0:
        rata_rating=0
        jumlah=0
        for r in pendaftaran:
            rata_rating+=r.rating
            jumlah+=1
        rata_rating = rata_rating/jumlah
        response['rata_rating'] = 'Rated ' + str(round(rata_rating,1)) +'/5'
    else:
        response['rata_rating'] = 'Belum ada rating'
        
    
    
    return render(request, "detail_kursus.html", response)

detail_kursus/templates/detail_kursus.html
{% extends 'app-shell.html' %}
{% load static %}

{% block meta %}
    <title>iTutor | Detail Kursus</title>
    <!-- <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width">
    <meta name="viewport" content="initial-scale = 1.0, maximum-scale = 1.0, user-scalable = no, width = device-width"> -->
    <!-- General Stylesheet-->
    <link href="{% static 'css/style.css' %}" type="text/css" rel="stylesheet" media="screen" />
{% endblock meta %}

{% block content %}

<!-- Chat button -->
    {% if pengguna.is_pelajar %}
    <a href="{% url 'pesan:add_contact_url' kursus.pengajar.id %}" class="float">
    <i class="far fa-comment"></i>&ensp;Chat Pengajar</a>
    {% elif pengguna.is_pengajar %}
    <a href="{% url 'pesan:contacts_url' %}" class="float">
        <i class="far fa-comment"></i>&ensp;Chat</a>
    {% endif %}


    <div style="padding-left: 64px;padding-right: 64px;margin-top: 100px;">
        {% if pengguna.is_pengajar %}
        <a href="{% url 'kursus_pengajar:kursus_pengajar' %}" class='button secondary yellow'>
            <i class="fa fa-arrow-left"></i>&ensp;Daftar Kursus
        </a><br><br><br>
        {% else %}
        <a href="{% url 'carikursus:cari_kursus' %}" class='button secondary yellow'>
            <i class="fa fa-arrow-left"></i>&ensp;Cari Kursus
        </a><br><br><br>
        {% endif %}
    </div>
    
    <section class="hero">
        <article class="hero-item" style="margin: 0;">
            <article class="vertical atas">
                <span style="font-size: 28px;color: #4956DF;">{{ kursus.kategori }}</span><br>
                <span style="font-size: 45px;font-weight: bolder;">{{ kursus.nama_kursus }}</span><br>
                <span style="font-size: 34px;color: #4956DF;font-weight: 400;">by {{ kursus.pengajar.first_name }}</span><br>   
            </article>
            <article class="vertical bawah">
                
                <span><button class='button secondary yellow' style="pointer-events: none;">{{ rata_rating }}</button>
                
                    {% if not pelajar_valid and pengguna.is_pelajar %}
                    <a href="{% url 'daftar_kursus:daftar_kursus' kursus.id %}"><button class='button primary'>Daftar Kursus</button></a></span>
                    {% endif %}
                
                
            </article>
        </article><!-- /card-one -->

        <article class="hero-item">
            <img src="{% static 'images/hero-img.svg' %}" alt="" title="">  
        </article><!-- /card-two -->
    </section>

    <section class="desc">
        <article class="hero-item" style="font-weight: 400;text-align: justify;">
            {{  kursus.deskripsi }}
        </article>
        <article class="hero-item" style="font-weight: 400;text-align: justify;">
            Lokasi kursus: {{  kursus.lokasi }}
        </article>
    </section>

    <section class="judul" style="padding-left: 64px;padding-right: 64px;margin-top: 100px;margin-bottom: 100px;">
        <span style="font-size: 28px;font-weight: 600;">Jadwal Ketersediaan Tutor</span><br><br>
        <table>
            <thead>
                <tr>
                <th style="font-weight: 700;">Hari</th>
                <!-- <th style="font-weight: 700;">Sesi</th> -->
                </tr>
            </thead>
            <tbody>
                {% for hari in kursus.jadwal %}
                <tr>
                <td>{{ hari }}</td>
                <!-- <td>13:00 - 15:00 | 17:00 - 19:00</td> -->
                </tr>
                {% endfor %}
                
            </tbody>
            </table>
    </section>

    <section class="feedback">
        <span style="font-size: 38px;font-weight: 600;color: white;">Apa kata mereka?</span><br><br>
        <section class="cardcontainer">
            {% for f in pendaftaran %}
            <section class="card">
                <p>{{ f.feedback }}</p>
                <p style="font-weight: 600;color: var(--yellow);">Rated {{ f.rating }}/5</p>
            </section>
            {% empty %}
            <p style='color:white; font-size: 24px;'>Belum ada feedback.</p>
            {% endfor %}

        </section>
    </section>

{% endblock content %}