detail_kursus/urls.py
from django.urls import path
from . import views

app_name = 'detail_kursus'
urlpatterns = [
    path('<int:id_kursus>',views.detail_kursus,name='detail_kursus'),
]

itutor/urls.py
from django import urls
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('', views.landing_page, name="landing_page"),
    path('admin/', admin.site.urls),
    path('authenticate/', include('login_logout.urls')),
    path('buat-kursus/', include('buat_kursus.urls')),
    path('sunting-kursus/', include('sunting_kursus.urls')),
    path('daftar-kursus/', include('daftar_kursus.urls')),
    path('detail-kursus/',include('detail_kursus.urls')),
    path('buat-feedback/',include('feedback.urls')),
    path('pengajuan-kursus/',include('pengajuan_kursus.urls')),
    path('pesan/', include('pesan.urls')),
    path('kursus-pengajar/', include('kursus_pengajar.urls')),
    path('verifikasi/', include('verifikasi_kursus.urls')),
    path('cari-kursus/', include('carikursus.urls')),
    path('register/', include('register.urls')),
    path('kursus-pelajar/', include('kursus_pelajar.urls')),
    path('profile-pengguna/', include('profile_pengguna.urls')),
]

kursus_pelajar/urls.py
from django.urls import path
from .views import kursus_pelajar, delete_pendaftaran, buat_feedback

app_name = 'kursus_pelajar'
urlpatterns = [
    path('', kursus_pelajar, name='kursus_pelajar'),
    path('delete/<int:pk>', delete_pendaftaran, name='delete_pendaftaran'),
    path('update/<int:id_pendaftaran>', buat_feedback, name='buat_feedback'),
]

pesan/urls.py
from django.urls import path
from . import views

app_name = 'pesan'
urlpatterns = [
    path('add-contact/<id_pengajar>', views.add_contact, name="add_contact_url"),
    path('contacts', views.show_all_contact, name="contacts_url"),
    path('detail/<username>', views.show_all_pesan, name="message_url"),
]

kursus_pelajar/models.py
from django.db import models

# Create your models here.

kursus_pelajar/forms.py
from django import forms
from django.forms import ModelForm, widgets
from daftar_kursus.models import Pendaftaran


CHOICES=[(1,'1'),
         (2,'2'),
         (3,'3'),
         (4,'4'),
         (5,'5')]

class FeedbackForm(ModelForm):
    class Meta:
        model = Pendaftaran
        fields = ('feedback', 'rating')
        widgets = {
            'feedback': forms.Textarea(attrs={'rows':5, 'placeholder':'Maksimal 500 Karakter', 'label':'feedback'}),
            'rating': forms.RadioSelect(
                attrs={'class':'form-check-input','id':'inlineRadio'}) 
        }

kursus_pelajar/views.py
from django.http import response
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from register.models import NonAdmin, Pelajar
from daftar_kursus.models import Pendaftaran
from django.contrib.auth.models import User
from .forms import FeedbackForm
from django.contrib import messages

@login_required(login_url='login_logout:login_url')
def kursus_pelajar(request):
    try:
        pelajar = Pelajar.objects.get(nonadmin_ptr_id=request.user.id)
    except:
        return render(request, "peringatun.html")
    print(pelajar.id)
    pendaftaran = pelajar.pendaftaran_set.all()
    print(pendaftaran)
    return render(request, "KursusPelajarNew.html", {'pendaftaran': pendaftaran})
    

def delete_pendaftaran(request, pk):
    pendaftaran = Pendaftaran.objects.get(id=pk)
    pendaftaran.delete()
    return redirect('kursus_pelajar:kursus_pelajar')

def buat_feedback(request, id_pendaftaran):
    pendaftaran = Pendaftaran.objects.get(id=id_pendaftaran)
    form = FeedbackForm()
    print('tesssss')
    print(request.method)
    if request.method == 'POST':
        form = FeedbackForm(request.POST)
        print(form)
        print(request.POST)
        print(form.is_valid())
        if form.is_valid():
            print("masuk")
            form_clean = form.cleaned_data
            pendaftaran.feedback = form_clean['feedback']
            pendaftaran.rating = form_clean['rating']
            pendaftaran.status_pendaftar = 3
            pendaftaran.save()
            return redirect('kursus_pelajar:kursus_pelajar')
    return render(request, "KursusPelajarNew.html", {'form':form})

kursus_pelajar/templates/KursusPelajar.html
{% extends 'app-shell.html' %}

{% load static %}

{% block meta %}
    <link rel="stylesheet" href="{% static 'css/kurpel.css' %}">
    <!-- CSS Modal -->
    <link rel="stylesheet" href="{% static 'css/modal.css' %}">
    <title>iTutor | Kursus Pelajar</title>
{% endblock meta %}

{% block content %}
    <div class="container-fluid">
        <div class="autolayout container">
            <div class="row bfr">
                <p id="rcorners0">Kursus yang kamu miliki</p>
            </div>
            {% for xx in pendaftaran %}
                <div class="row mtkul">
                    <div class = "col-7">
                        <div class = "row">
                            <a href="{% url 'detail_kursus:detail_kursus' xx.kursus_id %}">
                                <p id="rcorners2">{{xx.kursus.nama_kursus}}</p>
                            </a>
                        </div>
                        <div class = "row">
                            <p id="rcorners3">{{xx.kursus.pengajar.username}}</p>
                        </div>
                    </div>
                    <div class = "col-5">
                    {% if xx.status_pendaftar == 0 %}
                        <div class = "row">
                            <div class = "flex container">
                                <span id="rcornerspending">Belum Diterima</span>
                            </div>
                        </div>
                        <div class = "row">
                            <div class = "flex container">
                                <a ><button class="btn btn-default buttonhapus" onclick="toggleHapus('{{xx.id}}')">Batalkan Pengajuan</button></a>
                                <a ><button class="btn btn-default buttonedit">Lihat Pengajuan</button></a>
                            </div>   
                        </div>
                    {% elif xx.status_pendaftar == 1 %}
                        <div class = "row">
                            <div class = "flex container">
                                <span id="rcornersditolak">Ditolak</span>
                            </div>
                        </div>
                    {% elif xx.status_pendaftar == 2 %}
                        <div class = "row">
                            <div class = "flex container">
                                <span id="rcornersditerima">Diterima</span>
                            </div>
                        </div>
                        <div class = "row">
                            <div class = "flex container">
                                <a ><button class="btn btn-default buttonkon" onclick="togglePopup('{{xx.id}}')">Selesai</button></a>
                                <a ><button class="btn btn-default buttonkon">Kontak Pengajar</button></a>
                            </div>   
                        </div>
                    {% elif xx.status_pendaftar == 3 %}
                        <div class = "row">
                            <div class = "flex container">
                                <span id="rcornersditolak">Selesai</span>
                            </div>
                        </div>
                    {% endif %}
                </div>
            </div>

            {% endfor %}

            <!-- {% if message_error != "" %}
                            <p class="messages">{{ message_error }}</p>
                        {% else %}
                            <p>Masuk</p>
                        {% endif %} -->

            {% for xx in pendaftaran %}
                <!-- Form -->
                <div class="popup" id="popup-{{ xx.id }}">
                    <div class="overlay">
                    <div class="content">

                    <div class="close-btn" onclick="togglePopup('{{xx.id}}')">&times;</div><br>
                    <span style="font-family: 'Nunito',sans-serif;font-size: 28px;font-weight:700;">Form Feedback Kursus</span>
                    <hr>
                    <form id="form-daftar" action="{% url 'kursus_pelajar:buat_feedback' xx.id %}" method="POST">
                        {% csrf_token %}
                        <div class="form-group">
                            <label for="inputDeskripsiKursus">Feedback untuk pengajar</label><br>
                            <textarea type="text" class="form-control" id="inputFeedbackKursus" max="500" rows="5" placeholder="Maksimal 500 karakter"
                            name="feedback" value="{{ feedback }}" required></textarea>
                        </div>

                        

                        <span>Rating:&emsp;</span>
                        
                        <div class="form-check form-check-inline form-group">
                            <input class="form-check-input" type="radio" name="rating" id="inlineRadio" value=1>
                            <label class="form-check-label" for="inlineRadio1">1 star</label>
                        </div>
                        <div class="form-check form-check-inline">
                            <input class="form-check-input" type="radio" name="rating" id="inlineRadio" value=2>
                            <label class="form-check-label" for="inlineRadio2">2 star</label>
                        </div>
                        <div class="form-check form-check-inline">
                            <input class="form-check-input" type="radio" name="rating" id="inlineRadio" value=3>
                            <label class="form-check-label" for="inlineRadio3">3 star</label>
                        </div>
                        <div class="form-check form-check-inline">
                            <input class="form-check-input" type="radio" name="rating" id="inlineRadio" value=4>
                            <label class="form-check-label" for="inlineRadio4">4 star</label>
                        </div>
                        <div class="form-check form-check-inline">
                            <input class="form-check-input" type="radio" name="rating" id="inlineRadio" value=5 checked>
                            <label class="form-check-label" for="inlineRadio5">5 star</label>
                        </div>
                    <!-- </form> -->
                    <div class="flex-container">
                        <!-- <a href="{% url 'kursus_pelajar:buat_feedback' xx.id %}"> -->
                            <button type="submit" class="btn btn-default buttonhapus">Kirim</button>
                        <!-- </a> -->
                    </div>
                    </form>
                </div>
            
            </div>
                           
                    </div>
                </div>
             
                <div class="popup" id="popupz-{{ xx.id }}">
                    <div class="overlay">
                    <div class="content">
            
                        <div class="close-btn" onclick="toggleHapus('{{xx.id}}')">&times;</div><br><br>
                            <span style="font-family: 'Nunito',sans-serif;font-size: 28px;">Yakin ingin membatalkan?</span>
                        
                            <div class="flex-container">
                                <a href="{% url 'kursus_pelajar:delete_pendaftaran' xx.id %}">
                                    <button type="submit" class="btn btn-default buttonhapus" >Yakin</button>
                                </a>
                                <button type="submit" class="btn btn-default buttonedit" onclick="toggleHapus('{{xx.id}}')">Batal</button>
                            </div>
            
                        </div>
                            
                    </div>
            
                    </div>
                </div>

             {% endfor %}
             
            </div>

        </div>

    </div>
</div>

</div>

{% endblock content %}

{% block script %}
<script type="text/javascript">function togglePopup(id){
    document.getElementById(`popup-${id}`).classList.toggle("active");
  }</script>

<script type="text/javascript">function toggleHapus(id){
    document.getElementById(`popupz-${id}`).classList.toggle("active");
  }</script>
{% endblock script %}

kursus_pelajar/templates/KursusPelajarNew.html
{% extends 'app-shell.html' %}
{% load static %}

{% block meta %}
    <link rel="stylesheet" href="{% static 'css/kurpel.css' %}"/>
    <!-- CSS Modal -->
    <link rel="stylesheet" href="{% static 'css/modal.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/modilo.css' %}"/>
    <title>Kursus Pelajar</title>
{% endblock meta %}

{% block content %}
    <div class="content">  
        <div class="container-fluid">
            <div class="autolayout container">
                <div class="row bfr">
                    <p id="rcorners0">Kursus yang kamu miliki</p>
                </div>
                {% for xx in pendaftaran %}
                <div class="row mtkul">
                    <div class="col-7">
                        <div class="row">
                            <a href="{% url 'detail_kursus:detail_kursus' xx.kursus_id %}">
                                <p id="rcorners2">{{xx.kursus.nama_kursus}}</p>
                            </a>
                        </div>
                        <div class="row">
                            <p id="rcorners2">{{xx.kursus.pengajar.username}}</p>
                        </div>
                    </div>

                    <div class="col-5">
                    {% if xx.status_pendaftar == 0 %}
                        <div class="row">
                            <div class="flex container">
                                <span id="rcornerspending">Belum Diterima</span>
                            </div>
                        </div>
                        <div class = "row">
                            <div class = "flex container">
                                <a ><button class="btn btn-default buttonhapus" onclick="toggleHapus('{{xx.id}}')">Batalkan Pengajuan</button></a>
                                <a ><button class="btn btn-default buttonedit" onclick="toggleLihat('{{xx.id}}')">Lihat Pengajuan</button></a>
                            </div>   
                        </div>
                    {% elif xx.status_pendaftar == 1 %}
                        <div class = "row">
                            <div class = "flex container">
                                <span id="rcornersditolak">Ditolak</span>
                            </div>
                        </div>
                    {% elif xx.status_pendaftar == 2 %}
                        <div class = "row">
                            <div class = "flex container">
                                <span id="rcornersditerima">Diterima</span>
                            </div>
                        </div>
                        <div class = "row">
                            <div class = "flex container">
                                <a ><button class="btn btn-default buttonkon" onclick="togglePopup('{{xx.id}}')">Selesai</button></a>
                                <a href="{% url 'pesan:add_contact_url' xx.kursus.pengajar_id %}" class="float"><button class="btn btn-default buttonkon">Kontak Pengajar</button></a>
                            </div>   
                        </div>
                    {% elif xx.status_pendaftar == 3 %}
                        <div class = "row">
                            <div class = "flex container">
                                <span id="rcornersselesai">Selesai</span>
                            </div>
                        </div>
                    {% endif %}

                    </div>
                 </div>
                <!-- Form -->
                <div class="popup" id="popup-{{ xx.id }}">
                    <div class="overlay">
                        <div class="content">

                            <div class="close-btn" onclick="togglePopup('{{xx.id}}')">&times;</div><br>
                            <span style="font-family: 'Nunito',sans-serif;font-size: 28px;font-weight:700;">Form Feedback Kursus</span>
                            <hr>
                            <form id="form-daftar" action="{% url 'kursus_pelajar:buat_feedback' xx.id %}" method="POST">
                                {% csrf_token %}
                                <div class="form-group">
                                    
                                    <label for="inputDeskripsiKursus">Feedback untuk pengajar</label><br>
                                    <textarea type="text" class="form-control" id="inputFeedbackKursus" max="500" rows="5" placeholder="Maksimal 500 karakter"
                                    name="feedback" value="{{ feedback }}" required></textarea>
                                </div>

                                <span>Rating:&emsp;</span>
                                
                                <div class="form-check form-check-inline form-group">
                                    <input class="form-check-input" type="radio" name="rating" id="inlineRadio" value=1>
                                    <label class="form-check-label" for="inlineRadio1">1 star</label>
                                </div>
                                <div class="form-check form-check-inline">
                                    <input class="form-check-input" type="radio" name="rating" id="inlineRadio" value=2>
                                    <label class="form-check-label" for="inlineRadio2">2 star</label>
                                </div>
                                <div class="form-check form-check-inline">
                                    <input class="form-check-input" type="radio" name="rating" id="inlineRadio" value=3>
                                    <label class="form-check-label" for="inlineRadio3">3 star</label>
                                </div>
                                <div class="form-check form-check-inline">
                                    <input class="form-check-input" type="radio" name="rating" id="inlineRadio" value=4>
                                    <label class="form-check-label" for="inlineRadio4">4 star</label>
                                </div>
                                <div class="form-check form-check-inline">
                                    <input class="form-check-input" type="radio" name="rating" id="inlineRadio" value=5 checked>
                                    <label class="form-check-label" for="inlineRadio5">5 star</label>
                                </div>
                                <div class="flex-container">
                                    <!-- <a href="{% url 'kursus_pelajar:buat_feedback' xx.id %}"> -->
                                        <button type="submit" class="btn btn-default buttonhapus">Kirim</button>
                                    <!-- </a> -->
                                </div>
                            </form>
                            <!-- </form> -->
                            
                        </div>
                    
                    </div>
                </div>

             
                <div class="popup" id="popupz-{{ xx.id }}">
                    <div class="overlay">
                    <div class="content">
            
                        <div class="close-btn" onclick="toggleHapus('{{xx.id}}')">&times;</div><br><br>
                            <span style="font-family: 'Nunito',sans-serif;font-size: 28px;">Yakin ingin membatalkan?</span>
                        
                            <div class="flexy-container">
                                <a href="{% url 'kursus_pelajar:delete_pendaftaran' xx.id %}">
                                    <button type="submit" class="btn btn-default buttonhapus" >Yakin</button>
                                </a>
                                <button type="submit" class="btn btn-default buttonkon" onclick="toggleHapus('{{xx.id}}')">Batal</button>
                            </div>
                        </div>
                            
                    </div>
                </div>
                <div class="popup" id="popupx-{{ xx.id }}">
                    <div class="overlay">
                    <div class="content">
            
                        <div class="close-btn" onclick="toggleLihat('{{xx.id}}')">&times;</div><br><br>
                            <span id="rcorners5">{{xx.kursus.nama_kursus}}</span>
                            <br>
                            <br>
                            <div class="row">
                                <div class="col-3">
                                    <p id="rcorners4">Materi</p>
                                </div>
                                <div class="col-9">
                                    <p id="rcorners4">{{xx.materi}}</p>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-3">
                                    <p id="rcorners4">Harapan</p>
                                </div>
                                <div class="col-9">
                                    <p id="rcorners4">{{xx.harapan}}</p>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-3">
                                    <p id="rcorners4">Start Date</p>
                                </div>
                                <div class="col-9">
                                    <p id="rcorners4">{{xx.start_kursus}}</p>
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-3">
                                    <p id="rcorners4">Stop Date</p>
                                </div>
                                <div class="col-9">
                                    <p id="rcorners4">{{xx.stop_kursus}}</p>
                                </div>
                            </div>
                        
                        </div>
                    </div>
                </div>

            {% endfor %}
            
        </div>
    </div>
    </div>
    </div>
        
</div>  

{% endblock content %}

{% block script %}
<script type="text/javascript">function togglePopup(id){
    document.getElementById(`popup-${id}`).classList.toggle("active");
  }</script>

<script type="text/javascript">function toggleHapus(id){
    document.getElementById(`popupz-${id}`).classList.toggle("active");
  }</script>

<script type="text/javascript">function toggleLihat(id){
    document.getElementById(`popupx-${id}`).classList.toggle("active");
  }</script>
{% endblock script %}

kursus_pelajar/templates/peringatun.html
{% extends 'app-shell.html' %}

{% load static %}

{% block meta %}
    <link rel="stylesheet" href="{% static 'css/kurpeng.css' %}">
    <link rel="stylesheet" href="{% static 'css/modol.css' %}">
    <title>iTutor - Kursus Pelajar</title>
{% endblock meta %}

{% block content %}
<div class="content">
    <div class="container-fluid">
        <div class="autolayout container">
            <div class="row bfr">
                <div class="col">
                    <div class="row">
                        <p id="rcorners0">Whoopsie, kamu bukan pelajar</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>
</div>
{% endblock content %}